""" Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
max_number = int(input("Enter the number, "))
number1 = 3
number2 = 5
result = 0
index = 1
new_list = []
while index < max_number:
    print('checking for index = '+ str(index))
    is_divisible = (index%3 == 0 or index%5 ==0)
    print('is_divisble by 3 or 5 = '+str(is_divisible))
    if is_divisible:
        new_list.append(index)
        result = result + index	
    print('result so far = '+str(result))
    index += 1
print(result)
print(new_list)